[book]
authors = ["Thomas Butler", "drspacemn"]
language = "en"
multilingual = false
src = "src"
title = "Starknet Phone"

[output.html]
git-repository-url = "https://github.com/keep-starknet-strange/starknet-phone"
edit-url-template = "https://github.com/keep-starknet-strange/starknet-phone/issues/new/choose"
cname = "docs.starknetphone.xyz"
